// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"go-di-demo/pkg/common"
)

// Injectors from providers.go:

// InitializeUserManager creates a UserManager with all its dependencies
func InitializeUserManager() (*common.UserManager, error) {
	simpleLogger := common.NewSimpleLogger()
	inMemoryDB := common.NewInMemoryDB(simpleLogger)
	userService := common.NewUserService(inMemoryDB, simpleLogger)
	notificationService := common.NewNotificationService(simpleLogger)
	userManager := common.NewUserManager(userService, notificationService)
	return userManager, nil
}

// providers.go:

// Bind concrete implementations to interfaces
var LoggerSet = wire.NewSet(common.NewSimpleLogger, wire.Bind(new(common.Logger), new(*common.SimpleLogger)))

var DatabaseSet = wire.NewSet(common.NewInMemoryDB, wire.Bind(new(common.Database), new(*common.InMemoryDB)))

// ProviderSet is a Wire provider set with all the dependencies
var ProviderSet = wire.NewSet(
	LoggerSet,
	DatabaseSet, common.NewUserService, common.NewNotificationService, common.NewUserManager,
)
